### ISSUE TITLE
Unaligned mm_ptr causes segfault when mm_ptr assignment is optimized with movaps

### ISSUE THREAD

**Issue by zhaishuang1** [jiezhoucs/checkedc-llvm#2]
Currently, `mm_alloc()` and `mm_array_alloc()` (implemented at https://github.com/jzhou76/checkedc-safe-mm-misc/blob/040f08b50f7e022cb2dc033d65022362c1344501/lib/safe_mm_checked.c) put ID at the beginning of the memory allocated by `malloc()`(say **addr**). So the the actual struct will be placed at **addr + ID_SIZE**, where ID_SIZE is 8 bytes for our current implementation.

There is a problem when we have an MMSafePtr inside a struct. Because of the 8 bytes of ID before the real heap object, the alignment of the MMSafePtr would be 8 if the return address of `malloc` is aligned at 16 bytes. Under optimization level `-O1` or higher, llvm may emit `movaps` instruction with `xmm` registers  for x86 processors; however, `movaps` which requires the memory address alignment to be 16 bytes. Although we have designed in such a way that all MMSafePtr within a struct always have offset aligned to 16 bytes, the base address of the struct is not aligned; therefore `movaps` will trigger segfault.

One possible way to solve this is by using `movups`, which is equivalent to `movaps` but does not require memory address alignment. But we may need to think deeper about how the unalignment will possibly impact the programs/programmers. Another solution might be increasing the ID_SIZE to 16 bytes.

**Comment by jiezhoucs** [comment]
This issue has been temporarily solved by padding 8 more bytes at the beginning of a newly allocated heap object.
Related commit: https://github.com/jzhou76/checkedc-safe-mm-misc/commit/f6256cac9ae7a229866d6c5dc0748c2efd5f07ac
